"""Constants for TAC2100 Modbus energy meter."""

from __future__ import annotations

from typing import Final

DOMAIN: Final = "tac2100"

DEFAULT_NAME: Final = "TAC2100"
DEFAULT_PORT_TCP: Final = 502
DEFAULT_SLAVE: Final = 1
DEFAULT_SCAN_INTERVAL: Final = 30
DEFAULT_BAUDRATE: Final = 9600
DEFAULT_BYTESIZE: Final = 8
DEFAULT_PARITY: Final = "N"
DEFAULT_STOPBITS: Final = 1
DEFAULT_IMPORT_ENERGY_OFFSET: Final = 0.0
DEFAULT_EXPORT_ENERGY_OFFSET: Final = 0.0

CONF_CONNECTION_TYPE: Final = "connection_type"
CONF_SERIAL_PORT: Final = "serial_port"
CONF_BAUDRATE: Final = "baudrate"
CONF_BYTESIZE: Final = "bytesize"
CONF_PARITY: Final = "parity"
CONF_STOPBITS: Final = "stopbits"
CONF_HOST: Final = "host"
CONF_PORT: Final = "port"
CONF_SLAVE: Final = "slave"
CONF_SCAN_INTERVAL: Final = "scan_interval"
CONF_IMPORT_ENERGY_OFFSET: Final = "import_energy_offset"
CONF_EXPORT_ENERGY_OFFSET: Final = "export_energy_offset"

CONNECTION_TCP: Final = "tcp"
CONNECTION_RTU: Final = "rtu"

# Input registers (function 0x04), IEEE754 float, 2 registers each (TAC2100 Modbus Protocol v1.0)
REG_VOLTAGE: Final = 0x0000
REG_CURRENT: Final = 0x0006
REG_ACTIVE_POWER: Final = 0x000C
REG_REACTIVE_POWER: Final = 0x0012
REG_APPARENT_POWER: Final = 0x0018
REG_POWER_FACTOR: Final = 0x001E
REG_PHASE_ANGLE: Final = 0x0024
REG_FREQUENCY: Final = 0x0030
REG_LOAD_NATURE: Final = 0x004E
REG_ACTIVE_POWER_DEMAND: Final = 0x008C
REG_REACTIVE_POWER_DEMAND: Final = 0x008E
REG_APPARENT_POWER_DEMAND: Final = 0x0090
REG_CURRENT_DEMAND: Final = 0x0092
REG_IMPORT_ACTIVE_POWER_DEMAND: Final = 0x009A
REG_EXPORT_ACTIVE_POWER_DEMAND: Final = 0x009C
REG_MAX_ACTIVE_POWER_DEMAND: Final = 0x00A2
REG_MAX_REACTIVE_POWER_DEMAND: Final = 0x00A4
REG_MAX_APPARENT_POWER_DEMAND: Final = 0x00A6
REG_MAX_CURRENT_DEMAND: Final = 0x00A8
REG_MAX_IMPORT_ACTIVE_POWER_DEMAND: Final = 0x00B0
REG_MAX_EXPORT_ACTIVE_POWER_DEMAND: Final = 0x00B2
REG_TOTAL_IMPORT_ACTIVE_ENERGY: Final = 0x0500
REG_TOTAL_EXPORT_ACTIVE_ENERGY: Final = 0x0502
REG_TOTAL_ACTIVE_ENERGY: Final = 0x0504
REG_TOTAL_IMPORT_REACTIVE_ENERGY: Final = 0x0508
REG_TOTAL_EXPORT_REACTIVE_ENERGY: Final = 0x050A
REG_TOTAL_REACTIVE_ENERGY: Final = 0x050C

MODBUS_TIMEOUT: Final = 5
